name: Test report


on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

jobs:
  report:
    name: Test results
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          artifact: test-results
          name: Test report
          path: '*.xml'
          reporter: jest-junit

